### ISSUE TITLE
Pystan install not working

### ISSUE THREAD

**Issue by ericthansen** [learn-co-curriculum/dsc-facebook-prophet-lab#1]
## Link to Canvas

https://learning.flatironschool.com/courses/1890/assignments/126399?module_item_id=261929

## Issue Subtype

- [x ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
# If installing from terminal
# pip install pystan
# pip install fbprophet

# If installing from a jupyter notebook
# !pip install pystan
# !pip install fbprophet
```

### Concern

pystan install doesn't work on my system; even when changed to use an old version.

## What OS Are You Using?

- [ ] OS X
- [x ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by bpurdy-ds** [comment]
I had issues on ID as well, but now that it is on SC; it worked fine for me.
Closed commit: https://github.com/learn-co-curriculum/dsc-facebook-prophet-lab/issues/1#issue-1123375991
